import '../../ui/screens/main/tabs/quran/sura_dm.dart';
import 'app_assets.dart';

List<SuraDM> suras = [
  SuraDM(suraIndex: "1", nameAr: "الفاتحه", nameEn: "Al-Fatiha", verses: "7"),
  SuraDM(suraIndex: "2", nameAr: "البقرة", nameEn: "Al-Baqarah", verses: "286"),
  SuraDM(
    suraIndex: "3",
    nameAr: "آل عمران",
    nameEn: "Aal-E-Imran",
    verses: "200",
  ),
  SuraDM(suraIndex: "4", nameAr: "النساء", nameEn: "An-Nisa'", verses: "176"),
  SuraDM(
    suraIndex: "5",
    nameAr: "المائدة",
    nameEn: "Al-Ma'idah",
    verses: "120",
  ),
  SuraDM(suraIndex: "6", nameAr: "الأنعام", nameEn: "Al-An'am", verses: "165"),
  SuraDM(suraIndex: "7", nameAr: "الأعراف", nameEn: "Al-A'raf", verses: "206"),
  SuraDM(suraIndex: "8", nameAr: "الأنفال", nameEn: "Al-Anfal", verses: "75"),
  SuraDM(suraIndex: "9", nameAr: "التوبة", nameEn: "At-Tawbah", verses: "129"),
  SuraDM(suraIndex: "10", nameAr: "يونس", nameEn: "Yunus", verses: "109"),
  SuraDM(suraIndex: "11", nameAr: "هود", nameEn: "Hud", verses: "123"),
  SuraDM(suraIndex: "12", nameAr: "يوسف", nameEn: "Yusuf", verses: "111"),
  SuraDM(suraIndex: "13", nameAr: "الرعد", nameEn: "Ar-Ra'd", verses: "43"),
  SuraDM(suraIndex: "14", nameAr: "إبراهيم", nameEn: "Ibrahim", verses: "52"),
  SuraDM(suraIndex: "15", nameAr: "الحجر", nameEn: "Al-Hijr", verses: "99"),
  SuraDM(suraIndex: "16", nameAr: "النحل", nameEn: "An-Nahl", verses: "128"),
  SuraDM(suraIndex: "17", nameAr: "الإسراء", nameEn: "Al-Isra", verses: "111"),
  SuraDM(suraIndex: "18", nameAr: "الكهف", nameEn: "Al-Kahf", verses: "110"),
  SuraDM(suraIndex: "19", nameAr: "مريم", nameEn: "Maryam", verses: "98"),
  SuraDM(suraIndex: "20", nameAr: "طه", nameEn: "Ta-Ha", verses: "135"),
  SuraDM(
    suraIndex: "21",
    nameAr: "الأنبياء",
    nameEn: "Al-Anbiya",
    verses: "112",
  ),
  SuraDM(suraIndex: "22", nameAr: "الحج", nameEn: "Al-Hajj", verses: "78"),
  SuraDM(
    suraIndex: "23",
    nameAr: "المؤمنون",
    nameEn: "Al-Mu'minun",
    verses: "118",
  ),
  SuraDM(suraIndex: "24", nameAr: "النّور", nameEn: "An-Nur", verses: "64"),
  SuraDM(suraIndex: "25", nameAr: "الفرقان", nameEn: "Al-Furqan", verses: "77"),
  SuraDM(
    suraIndex: "26",
    nameAr: "الشعراء",
    nameEn: "Ash-Shu'ara",
    verses: "227",
  ),
  SuraDM(suraIndex: "27", nameAr: "النّمل", nameEn: "An-Naml", verses: "93"),
  SuraDM(suraIndex: "28", nameAr: "القصص", nameEn: "Al-Qasas", verses: "88"),
  SuraDM(
    suraIndex: "29",
    nameAr: "العنكبوت",
    nameEn: "Al-Ankabut",
    verses: "69",
  ),
  SuraDM(suraIndex: "30", nameAr: "الرّوم", nameEn: "Ar-Rum", verses: "60"),
  SuraDM(suraIndex: "31", nameAr: "لقمان", nameEn: "Luqman", verses: "34"),
  SuraDM(suraIndex: "32", nameAr: "السجدة", nameEn: "As-Sajda", verses: "30"),
  SuraDM(suraIndex: "33", nameAr: "الأحزاب", nameEn: "Al-Ahzab", verses: "73"),
  SuraDM(suraIndex: "34", nameAr: "سبأ", nameEn: "Saba", verses: "54"),
  SuraDM(suraIndex: "35", nameAr: "فاطر", nameEn: "Fatir", verses: "45"),
  SuraDM(suraIndex: "36", nameAr: "يس", nameEn: "Ya-Sin", verses: "83"),
  SuraDM(
    suraIndex: "37",
    nameAr: "الصافات",
    nameEn: "As-Saffat",
    verses: "182",
  ),
  SuraDM(suraIndex: "38", nameAr: "ص", nameEn: "Sad", verses: "88"),
  SuraDM(suraIndex: "39", nameAr: "الزمر", nameEn: "Az-Zumar", verses: "75"),
  SuraDM(suraIndex: "40", nameAr: "غافر", nameEn: "Ghafir", verses: "85"),
  SuraDM(suraIndex: "41", nameAr: "فصّلت", nameEn: "Fussilat", verses: "54"),
  SuraDM(suraIndex: "42", nameAr: "الشورى", nameEn: "Ash-Shura", verses: "53"),
  SuraDM(suraIndex: "43", nameAr: "الزخرف", nameEn: "Az-Zukhruf", verses: "89"),
  SuraDM(suraIndex: "44", nameAr: "الدّخان", nameEn: "Ad-Dukhan", verses: "59"),
  SuraDM(
    suraIndex: "45",
    nameAr: "الجاثية",
    nameEn: "Al-Jathiya",
    verses: "37",
  ),
  SuraDM(suraIndex: "46", nameAr: "الأحقاف", nameEn: "Al-Ahqaf", verses: "35"),
  SuraDM(suraIndex: "47", nameAr: "محمد", nameEn: "Muhammad", verses: "38"),
  SuraDM(suraIndex: "48", nameAr: "الفتح", nameEn: "Al-Fath", verses: "29"),
  SuraDM(
    suraIndex: "49",
    nameAr: "الحجرات",
    nameEn: "Al-Hujurat",
    verses: "18",
  ),
  SuraDM(suraIndex: "50", nameAr: "ق", nameEn: "Qaf", verses: "45"),
  SuraDM(
    suraIndex: "51",
    nameAr: "الذاريات",
    nameEn: "Adh-Dhariyat",
    verses: "60",
  ),
  SuraDM(suraIndex: "52", nameAr: "الطور", nameEn: "At-Tur", verses: "49"),
  SuraDM(suraIndex: "53", nameAr: "النجم", nameEn: "An-Najm", verses: "62"),
  SuraDM(suraIndex: "54", nameAr: "القمر", nameEn: "Al-Qamar", verses: "55"),
  SuraDM(suraIndex: "55", nameAr: "الرحمن", nameEn: "Ar-Rahman", verses: "78"),
  SuraDM(suraIndex: "56", nameAr: "الواقعة", nameEn: "Al-Waqi'a", verses: "96"),
  SuraDM(suraIndex: "57", nameAr: "الحديد", nameEn: "Al-Hadid", verses: "29"),
  SuraDM(
    suraIndex: "58",
    nameAr: "المجادلة",
    nameEn: "Al-Mujadila",
    verses: "22",
  ),
  SuraDM(suraIndex: "59", nameAr: "الحشر", nameEn: "Al-Hashr", verses: "24"),
  SuraDM(
    suraIndex: "60",
    nameAr: "الممتحنة",
    nameEn: "Al-Mumtahina",
    verses: "13",
  ),
  SuraDM(suraIndex: "61", nameAr: "الصف", nameEn: "As-Saff", verses: "14"),
  SuraDM(suraIndex: "62", nameAr: "الجمعة", nameEn: "Al-Jumu'a", verses: "11"),
  SuraDM(
    suraIndex: "63",
    nameAr: "المنافقون",
    nameEn: "Al-Munafiqun",
    verses: "11",
  ),
  SuraDM(
    suraIndex: "64",
    nameAr: "التغابن",
    nameEn: "At-Taghabun",
    verses: "18",
  ),
  SuraDM(suraIndex: "65", nameAr: "الطلاق", nameEn: "At-Talaq", verses: "12"),
  SuraDM(suraIndex: "66", nameAr: "التحريم", nameEn: "At-Tahrim", verses: "12"),
  SuraDM(suraIndex: "67", nameAr: "الملك", nameEn: "Al-Mulk", verses: "30"),
  SuraDM(suraIndex: "68", nameAr: "القلم", nameEn: "Al-Qalam", verses: "52"),
  SuraDM(suraIndex: "69", nameAr: "الحاقة", nameEn: "Al-Haqqah", verses: "52"),
  SuraDM(
    suraIndex: "70",
    nameAr: "المعارج",
    nameEn: "Al-Ma'arij",
    verses: "44",
  ),
  SuraDM(suraIndex: "71", nameAr: "نوح", nameEn: "Nuh", verses: "28"),
  SuraDM(suraIndex: "72", nameAr: "الجن", nameEn: "Al-Jinn", verses: "28"),
  SuraDM(
    suraIndex: "73",
    nameAr: "المزّمّل",
    nameEn: "Al-Muzzammil",
    verses: "20",
  ),
  SuraDM(
    suraIndex: "74",
    nameAr: "المدّثر",
    nameEn: "Al-Muddathir",
    verses: "56",
  ),
  SuraDM(
    suraIndex: "75",
    nameAr: "القيامة",
    nameEn: "Al-Qiyamah",
    verses: "40",
  ),
  SuraDM(suraIndex: "76", nameAr: "الإنسان", nameEn: "Al-Insan", verses: "31"),
  SuraDM(
    suraIndex: "77",
    nameAr: "المرسلات",
    nameEn: "Al-Mursalat",
    verses: "50",
  ),
  SuraDM(suraIndex: "78", nameAr: "النبأ", nameEn: "An-Naba'", verses: "40"),
  SuraDM(
    suraIndex: "79",
    nameAr: "النازعات",
    nameEn: "An-Nazi'at",
    verses: "46",
  ),
  SuraDM(suraIndex: "80", nameAr: "عبس", nameEn: "Abasa", verses: "42"),
  SuraDM(suraIndex: "81", nameAr: "التكوير", nameEn: "At-Takwir", verses: "29"),
  SuraDM(
    suraIndex: "82",
    nameAr: "الإنفطار",
    nameEn: "Al-Infitar",
    verses: "19",
  ),
  SuraDM(
    suraIndex: "83",
    nameAr: "المطفّفين",
    nameEn: "Al-Mutaffifin",
    verses: "36",
  ),
  SuraDM(
    suraIndex: "84",
    nameAr: "الإنشقاق",
    nameEn: "Al-Inshiqaq",
    verses: "25",
  ),
  SuraDM(suraIndex: "85", nameAr: "البروج", nameEn: "Al-Buruj", verses: "22"),
  SuraDM(suraIndex: "86", nameAr: "الطارق", nameEn: "At-Tariq", verses: "17"),
  SuraDM(suraIndex: "87", nameAr: "الأعلى", nameEn: "Al-A'la", verses: "19"),
  SuraDM(
    suraIndex: "88",
    nameAr: "الغاشية",
    nameEn: "Al-Ghashiyah",
    verses: "26",
  ),
  SuraDM(suraIndex: "89", nameAr: "الفجر", nameEn: "Al-Fajr", verses: "30"),
  SuraDM(suraIndex: "90", nameAr: "البلد", nameEn: "Al-Balad", verses: "20"),
  SuraDM(suraIndex: "91", nameAr: "الشمس", nameEn: "Ash-Shams", verses: "15"),
  SuraDM(suraIndex: "92", nameAr: "الليل", nameEn: "Al-Lail", verses: "21"),
  SuraDM(suraIndex: "93", nameAr: "الضحى", nameEn: "Ad-Duha", verses: "11"),
  SuraDM(suraIndex: "94", nameAr: "الشرح", nameEn: "Ash-Sharh", verses: "8"),
  SuraDM(suraIndex: "95", nameAr: "التين", nameEn: "At-Tin", verses: "5"),
  SuraDM(suraIndex: "96", nameAr: "العلق", nameEn: "Al-Alaq", verses: "19"),
  SuraDM(suraIndex: "97", nameAr: "القدر", nameEn: "Al-Qadr", verses: "5"),
  SuraDM(suraIndex: "98", nameAr: "البينة", nameEn: "Al-Bayyina", verses: "8"),
  SuraDM(
    suraIndex: "99",
    nameAr: "الزلزلة",
    nameEn: "Az-Zalzalah",
    verses: "8",
  ),
  SuraDM(
    suraIndex: "100",
    nameAr: "العاديات",
    nameEn: "Al-Adiyat",
    verses: "11",
  ),
  SuraDM(
    suraIndex: "101",
    nameAr: "القارعة",
    nameEn: "Al-Qari'a",
    verses: "11",
  ),
  SuraDM(
    suraIndex: "102",
    nameAr: "التكاثر",
    nameEn: "At-Takathur",
    verses: "8",
  ),
  SuraDM(suraIndex: "103", nameAr: "العصر", nameEn: "Al-Asr", verses: "3"),
  SuraDM(suraIndex: "104", nameAr: "الهمزة", nameEn: "Al-Humazah", verses: "9"),
  SuraDM(suraIndex: "105", nameAr: "الفيل", nameEn: "Al-Fil", verses: "5"),
  SuraDM(suraIndex: "106", nameAr: "قريش", nameEn: "Quraysh", verses: "4"),
  SuraDM(suraIndex: "107", nameAr: "الماعون", nameEn: "Al-Ma'un", verses: "6"),
  SuraDM(suraIndex: "108", nameAr: "الكوثر", nameEn: "Al-Kawthar", verses: "3"),
  SuraDM(
    suraIndex: "109",
    nameAr: "الكافرون",
    nameEn: "Al-Kafirun",
    verses: "6",
  ),
  SuraDM(suraIndex: "110", nameAr: "النصر", nameEn: "An-Nasr", verses: "3"),
  SuraDM(suraIndex: "111", nameAr: "المسد", nameEn: "Al-Masad", verses: "5"),
  SuraDM(suraIndex: "112", nameAr: "الإخلاص", nameEn: "Al-Ikhlas", verses: "4"),
  SuraDM(suraIndex: "113", nameAr: "الفلق", nameEn: "Al-Falaq", verses: "5"),
  SuraDM(suraIndex: "114", nameAr: "الناس", nameEn: "An-Nas", verses: "6"),
];
List<String> tasbeha = ["سبحان الله", "الحمد لله", "الله أكبر"];
final List<Map<String, String>> pages = [
  {
    "image": AppAssets.introImg1,
    "title": "Welcome To Islami App",
    "desc": "",
  },
  {
    "image": AppAssets.introImg2,
    "title": "Welcome To Islami",
    "desc": "We Are Very Excited To Have You In Our Community",
  },
  {
    "image": AppAssets.introImg3,
    "title": "Reading the Quran",
    "desc": "Read, and your Lord is the Most Generous",
  },
  {
    "image": AppAssets.introImg4,
    "title": "Bearish",
    "desc": "Praise the name of your Lord, the Most High",
  },
  {
    "image": AppAssets.introImg5,
    "title": "Holy Quran Radio",
    "desc":
    "You can listen to the Holy Quran Radio through the application for free and easily",
  },
];